ALTER TYPE "Currency" ADD VALUE IF NOT EXISTS 'GBP';
ALTER TYPE "Currency" ADD VALUE IF NOT EXISTS 'CAD';
ALTER TYPE "Currency" ADD VALUE IF NOT EXISTS 'AUD';
ALTER TYPE "Currency" ADD VALUE IF NOT EXISTS 'SEK';
ALTER TYPE "Currency" ADD VALUE IF NOT EXISTS 'NOK';
ALTER TYPE "Currency" ADD VALUE IF NOT EXISTS 'CHF';
ALTER TYPE "Currency" ADD VALUE IF NOT EXISTS 'JPY';
